### ISSUE TITLE
Test binary fails to load libtorrent shared object

### ISSUE THREAD

**Issue by winterqt** [jesec/libtorrent#1]
```
error while loading shared libraries: libtorrent.so.21: cannot open shared object file: No such file or directory
```

See https://github.com/NixOS/nixpkgs/pull/121058#discussion_r628025723 for additional context.

**Comment by jesec** [comment]
I can not reproduce. 

```
$ cmake .
...
...

$ make -j32
...
...

$ make test
Running tests...
Test project /home/jc/rt/libtorrent
        Start   1: test_tracker_http.test_basic
  1/171 Test   #1: test_tracker_http.test_basic ...............................................   Passed    0.00 sec
...
```

**Comment by jesec** [comment]
You should build `libtorrent.so.21` before running `libtorrent_test`, and place them together.

**Comment by dotlambda** [comment]
But usually you would run `cd build && cmake ..`, not `cmake .`. The library should still be found.

**Comment by jesec** [comment]
Still I can't reproduce.

```bash
$ cmake -B build . && cmake --build build
...
...

$ ./build/libtorrent_test
[==========] Running 171 tests from 29 test suites.
[----------] Global test environment set-up.
...
...
```

```bash
$ cmake ..
...
...

$ make
...
...

$ ./libtorrent_test
[==========] Running 171 tests from 29 test suites.
[----------] Global test environment set-up.
...
```

**Comment by dotlambda** [comment]
I can reproduce it using
```sh
mkdir build
cd build
cmake -DCMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY=OFF -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_SKIP_BUILD_RPATH=ON ..
make
```

**Comment by jesec** [comment]
`CMAKE_SKIP_BUILD_RPATH=ON` does not work well with `gtest_discover_tests`:
```
/home/jc/rt/libtorrent/build/libtorrent_test: error while loading shared libraries: libtorrent.so.21: cannot open shared object file: No such file or directory
CMake Error at /usr/share/cmake-3.16/Modules/GoogleTestAddTests.cmake:40 (message):
  Error running test executable.
```

We can get the binary after removing `gtest_discover_tests` (that breaks "make test", though). Then, due to `CMAKE_SKIP_BUILD_RPATH`:
```sh
$ ./libtorrent_test
./libtorrent_test: error while loading shared libraries: libtorrent.so.21: cannot open shared object file: No such file or directory
```

Finally, with `LD_LIBRARY_PATH`, it works:
```sh
$ LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`pwd` ./libtorrent_test
[==========] Running 171 tests from 29 test suites.
[----------] Global test environment set-up.
[----------] 1 test from test_tracker_http
```

**Comment by winterqt** [comment]
Thanks @jesec, that helped. However, now this happens:

```
running tests
check flags: SHELL=/nix/store/a4yw1svqqk4d8lhwinn9xp847zz9gfma-bash-4.4-p23/bin/bash VERBOSE=y test
Running tests...
/nix/store/zzqzl5lm59mc04fd8f1wbwl7nmxvv1bb-cmake-3.19.7/bin/ctest --force-new-ctest-process 
Test project /build/source/build
```

Apologies for the ignorance, but I'm not sure if this is expected or not. (not too familiar with GoogleTest.)

**Comment by jesec** [comment]
> Thanks @jesec, that helped. However, now this happens:
> 
> ```
> running tests
> check flags: SHELL=/nix/store/a4yw1svqqk4d8lhwinn9xp847zz9gfma-bash-4.4-p23/bin/bash VERBOSE=y test
> Running tests...
> /nix/store/zzqzl5lm59mc04fd8f1wbwl7nmxvv1bb-cmake-3.19.7/bin/ctest --force-new-ctest-process 
> Test project /build/source/build
> ```
> 
> Apologies for the ignorance, but I'm not sure if this is expected or not. (not too familiar with GoogleTest.)

ctest (`make test`) would not work when the `discover_tests` is disabled. Simply run the `libtorrent_test` executable instead with appropriate `LD_LIBRARY_PATH`.

**Comment by jesec** [comment]
a38205c should resolve the issue. Though, note that the test output is a bit less nicer without `discover_tests`:

w/o:

```
Running tests...
Test project /home/jc/rt/libtorrent
    Start 1: libtorrent_test
1/1 Test #1: libtorrent_test ..................   Passed   16.15 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =  16.15 sec
```

w/:

```
Running tests...
Test project /home/jc/rt/libtorrent
        Start   1: test_tracker_http.test_basic
  1/171 Test   #1: test_tracker_http.test_basic ...............................................   Passed    0.00 sec
        Start   2: test_uri_parser.test_basic
  2/171 Test   #2: test_uri_parser.test_basic .................................................   Passed    0.00 sec
        Start   3: test_uri_parser.test_basic_magnet
  3/171 Test   #3: test_uri_parser.test_basic_magnet ..........................................   Passed    0.00 sec
        Start   4: test_uri_parser.test_query_magnet
...
```

**Comment by winterqt** [comment]
Thank you. Do you mind tagging an `r3` or similar including this commit?

**Comment by jesec** [comment]
Does it work?

**Comment by winterqt** [comment]
Apolgies for asking for a tag. (I forgot I can apply patches myself, lol.)

Additionally, it does not work:
```
running tests
check flags: SHELL=/nix/store/a4yw1svqqk4d8lhwinn9xp847zz9gfma-bash-4.4-p23/bin/bash VERBOSE=y test
Running tests...
/nix/store/zzqzl5lm59mc04fd8f1wbwl7nmxvv1bb-cmake-3.19.7/bin/ctest --force-new-ctest-process 
Test project /build/source/build
    Start 1: libtorrent_test
1/1 Test #1: libtorrent_test ..................***Failed    0.00 sec
/build/source/build/libtorrent_test: error while loading shared libraries: libtorrent.so.21: cannot open shared object file: No such file or directory


0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.00 sec

The following tests FAILED:
          1 - libtorrent_test (Failed)
Errors while running CTest
make: *** [Makefile:137: test] Error 8
```

Is this on my end or yours? I'm presuming mine, but not sure what to actually fix.

**Comment by jesec** [comment]
> Apolgies for asking for a tag. (I forgot I can apply patches myself, lol.)
> 
> Additionally, it does not work:
> 
> ```
> running tests
> check flags: SHELL=/nix/store/a4yw1svqqk4d8lhwinn9xp847zz9gfma-bash-4.4-p23/bin/bash VERBOSE=y test
> Running tests...
> /nix/store/zzqzl5lm59mc04fd8f1wbwl7nmxvv1bb-cmake-3.19.7/bin/ctest --force-new-ctest-process 
> Test project /build/source/build
>     Start 1: libtorrent_test
> 1/1 Test #1: libtorrent_test ..................***Failed    0.00 sec
> /build/source/build/libtorrent_test: error while loading shared libraries: libtorrent.so.21: cannot open shared object file: No such file or directory
> 
> 
> 0% tests passed, 1 tests failed out of 1
> 
> Total Test time (real) =   0.00 sec
> 
> The following tests FAILED:
>           1 - libtorrent_test (Failed)
> Errors while running CTest
> make: *** [Makefile:137: test] Error 8
> ```
> 
> Is this on my end or yours? I'm presuming mine, but not sure what to actually fix.

LD_LIBRARY_PATH

**Comment by winterqt** [comment]
> LD_LIBRARY_PATH

That works:
```
Running tests...
/nix/store/zzqzl5lm59mc04fd8f1wbwl7nmxvv1bb-cmake-3.19.7/bin/ctest --force-new-ctest-process 
Test project /build/source/build
    Start 1: libtorrent_test
1/1 Test #1: libtorrent_test ..................   Passed   16.11 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =  16.11 sec
```
Thanks for taking your time to help with this issue, appreciated.
