### ISSUE TITLE
Add build instructions

### ISSUE THREAD

**Issue by HarryMuscle** [jesec/libtorrent#2]
On the https://github.com/jesec/rtorrent page it states that building libtorrent is required before building rTorrent where amongst other instructions it says:

```
# Compile and install libtorrent (matching version required)
# Check README of libtorrent for instructions
```

Unfortunately the readme file in the libtorrent repo does not contain any building instructions.

**Comment by jesec** [comment]
The part only applies if you insist on using CMake. The procedure is the same as any regular CMake project, and you should already know that if you insist on using CMake.

**Comment by HarryMuscle** [comment]
> The part only applies if you insist on using CMake. The procedure is the same as any regular CMake project, and you should already know that if you insist on using CMake.

Do you normally build your releases using Bazel?  I tried compiling your rTorrent (tag v0.9.8-r15) using Bazel but my binary file comes out several hundred kb smaller, so I'm guessing you compile yours differently somehow.  Also, my binaries don't end up in any bazel-bin directory but are buried deep in a .cache directory in my home directory.  Would you mind sharing more details about your build setup?  I'm guessing I'm probably missing an option or two for bazel to match exactly what you are doing to create your releases.

**Comment by jesec** [comment]
Yes. Releases are made with Bazel. Bazel provides fine-grained control over dependencies. 

See https://github.com/jesec/rtorrent/blob/master/Dockerfile.

You may also check CI workflows: https://github.com/jesec/rtorrent/tree/master/.github/workflows

**Comment by HarryMuscle** [comment]
> Yes. Releases are made with Bazel. Bazel provides fine-grained control over dependencies.
> 
> See https://github.com/jesec/rtorrent/blob/master/Dockerfile.
> 
> You may also check CI workflows: https://github.com/jesec/rtorrent/tree/master/.github/workflows

Thanks.  I definitely am still missing something.  Running the docker build process on tag v0.9.8-r15 results in the following error during the buid:
```
Error relocating /usr/bin/bazel-real: _ZSt28__throw_bad_array_new_lengthv: symbol not found
```
Based on google searches this seems to be related to glibc mismatch issues.  I'm running this on a Ubuntu system, but I have a feeling you are building this image on a different Linux distribution and that's why it works for you and not on my end.  Which Linux distribution and version do you build your docker images on?

**Comment by jesec** [comment]
> > Yes. Releases are made with Bazel. Bazel provides fine-grained control over dependencies.
> > See https://github.com/jesec/rtorrent/blob/master/Dockerfile.
> > You may also check CI workflows: https://github.com/jesec/rtorrent/tree/master/.github/workflows
> 
> Thanks. I definitely am still missing something. Running the docker build process on tag v0.9.8-r15 results in the following error during the buid:
> 
> ```
> Error relocating /usr/bin/bazel-real: _ZSt28__throw_bad_array_new_lengthv: symbol not found
> ```
> 
> Based on google searches this seems to be related to glibc mismatch issues. I'm running this on a Ubuntu system, but I have a feeling you are building this image on a different Linux distribution and that's why it works for you and not on my end. Which Linux distribution and version do you build your docker images on?

You may need this: https://github.com/jesec/rtorrent/commit/5040a8eaeb876a2e21314b1fa22dbc85636fa015.

You don't have to build the Dockerfile. I posted the link, so you can see how the release was made.

You can run Bazel on Ubuntu as well. Just follow the instructions of README in rTorrent repo.
